# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytf" do
  name "lazytf"
  desc "Terminal UI for reviewing Terraform plans"
  homepage "https://github.com/ushiradineth/lazytf"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazytf"

  on_macos do
    on_intel do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_darwin_x86_64.tar.gz"
      sha256 "0d92b2336015a10e28e9c244ba5ccb567cf583b1da292dde7a6b984494833271"
    end
    on_arm do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_darwin_arm64.tar.gz"
      sha256 "9b03e636c34797b2cb157224100c451bdb0da5bea95c704d268cf427e270ad37"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_linux_x86_64.tar.gz"
      sha256 "52ba38b341c1d15561b652c92270beafa7b48a8ffec9cb69522d8ae3a50595c9"
    end
    on_arm do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_linux_arm64.tar.gz"
      sha256 "088977e796ff9026a2fbaddfa8ac1a2cf9d270030cc2674763bf59b40c689641"
    end
  end

  caveats do
    "If macOS blocks execution, run:"
    "xattr -dr com.apple.quarantine $(which lazytf)"
  end

  # No zap stanza required
end
