# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytf" do
  name "lazytf"
  desc "Terminal UI for reviewing Terraform plans"
  homepage "https://github.com/ushiradineth/lazytf"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazytf"

  on_macos do
    on_intel do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_darwin_x86_64.tar.gz"
      sha256 "975ab8e2fe365ae1a04f6fdfea18a25634acb31e678e5724899fd0864c6e9eb4"
    end
    on_arm do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_darwin_arm64.tar.gz"
      sha256 "b35ddfe85686aacb454094cdb86fa662c14c02d84193c14cfbc7c4940736eaae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_linux_x86_64.tar.gz"
      sha256 "e25055ca58b5b889518b23805d07a742065898e6d88eacdfac32ac4ae74c26b9"
    end
    on_arm do
      url "https://github.com/ushiradineth/lazytf/releases/download/v#{version}/lazytf_#{version}_linux_arm64.tar.gz"
      sha256 "b7b38d6deec47ca9eb720f141019443bfc59fd3bc13321c5a30bf7a98f984c29"
    end
  end

  caveats do
    "If macOS blocks execution, run:"
    "xattr -dr com.apple.quarantine $(which lazytf)"
  end

  # No zap stanza required
end
